### PR TITLE
fix issue "module not found"

### PR DESCRIPTION
**Pull request by DineshValor**
Screenshot_20220306-031540

Issue fixed "module not found" for termux user.

Screenshot_20220306-032013

### CODE REVIEW

**Comment by LorranX** [comment]
Fix yourself

Just edit package.json adding the missing module, It's not that difficult

**Comment by DineshValor** [comment]
> Fix yourself
> 
> Just edit package.json adding the missing module, It's not that difficult

I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅

**Comment by LorranX** [comment]
> > Fix yourself
> > 
> > Just edit package.json adding the missing module, It's not that difficult
> 
> I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅

😳

**Comment by DineshValor** [comment]
> > > Fix yourself
> > > Just edit package.json adding the missing module, It's not that difficult
> > 
> > 
> > I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅
> 
> 😳

Can you help me one more time😅
I'm unable get footer text in menu! What is the code line to add footer and where need to add that line🥲

**Comment by LorranX** [comment]
> > > > Fix yourself
> > > > Just edit package.json adding the missing module, It's not that difficult
> > > 
> > > 
> > > I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅
> > 
> > 😳
> 
> Can you help me one more time😅
> I'm unable to get footer text in menu! What is the code line to add footer and where need to add that line🥲

On template message some features are unavailable, such as bolding the text or adding any other text effect, but adding footer text shouldn't be difficult, i Will tive u an example on hisoka's code

hisoka.send5ButImg(jid , text , footer, image, buttons, options)

Only use this form, in this order

**Comment by DineshValor** [comment]
> > > > > Fix yourself
> > > > > Just edit package.json adding the missing module, It's not that difficult
> > > > 
> > > > 
> > > > I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅
> > > 
> > > 
> > > 😳
> > 
> > 
> > Can you help me one more time😅
> > I'm unable to get footer text in menu! What is the code line to add footer and where need to add that line🥲
> 
> On template message some features are unavailable, such as bolding the text or adding any other text effect, but adding footer text shouldn't be difficult, i Will tive u an example on hisoka's code
> 
> hisoka.send5ButImg(jid , text , footer, image, buttons, options)
> 
> Only use this form, in this order

Thanx a lot

**Comment by DineshValor** [comment]
> > > > > Fix yourself
> > > > > Just edit package.json adding the missing module, It's not that difficult
> > > > 
> > > > 
> > > > I guess you didn't caught my point, actually i told and give both issue & solution, so i pushed pull request to resolve it here too😅
> > > 
> > > 
> > > 😳
> > 
> > 
> > Can you help me one more time😅
> > I'm unable to get footer text in menu! What is the code line to add footer and where need to add that line🥲
> 
> On template message some features are unavailable, such as bolding the text or adding any other text effect, but adding footer text shouldn't be difficult, i Will tive u an example on hisoka's code
> 
> hisoka.send5ButImg(jid , text , footer, image, buttons, options)
> 
> Only use this form, in this order

What should i need to put at the place of `options`?

**Pull request closed without merging**
