### PR TITLE
added movie and fact command.

### PR DESCRIPTION
**Pull request by SamPandey001**

### CODE REVIEW

**Comment by DikaArdnt** [comment]
> _ No description provided. _

Ril or fact?

**Comment by SamPandey001** [comment]
> > _ No description provided. _
> 
> Ril or fact?

Fact

**Comment by FatihArridho** [comment]
LoL, ReferenceError: dgxeon not definied

**Comment by FatihArridho** [comment]
Janji gak pakai xfarr api?😅

**Pull request closed without merging**
